### ISSUE TITLE
hugegraph开启Kerberos后，使用hugegraph-loader.sh测试官方例子报错

### ISSUE THREAD

**Issue by wanglunwei** [apache/incubator-hugegraph-toolchain#226]
### Bug Type (问题类型)

exception / error (导入时异常报错):hugegraph开启Kerberos后，使用hugegraph-loader.sh测试官方例子报错,不开启Kerberos loader成功

### Environment (环境信息)

- Server Version: v0.11.2
- Loader Version: v0.11.1
- Data Size:  xx vertices, xx edges 
- hbase hdp版本：2.0.0.3.1
- zk hdp版本：3.4.9.3.1

### Expected & Actual behavior (期望与实际表现)

在使用hugegraph-loader.sh导入到开启Kerberos的hugegraph报错，但是导入没有开启Kerberos的hugegraph时成功的，备注：使用的官方的案例：sh bin/hugegraph-loader.sh -g hugegraph -f example/file/struct.json -s example/file/schema.groovy　　在实际执行过程中会添加上IP和port
以下时开启Kerberos报错信息：
2021-08-13 10:53:01 [Thread-3] [INFO ] c.b.h.l.HugeGraphLoader [] - Shutdown hook was triggered
2021-08-13 11:42:35 [main] [ERROR] c.b.h.l.u.Printer [] - Failed to load, cause: java.io.InterruptedIOException
com.baidu.hugegraph.exception.ServerException: java.io.InterruptedIOException
at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:172) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
at com.baidu.hugegraph.api.schema.PropertyKeyAPI.create(PropertyKeyAPI.java:46) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:79) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:142) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:125) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
at com.sun.proxy.$Proxy49.create(Unknown Source) ~[?:?]
at com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source) ~[?:?]
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.6.jar:2.4.6]
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-all-2.4.6.jar:2.4.6]
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-all-2.4.6.jar:2.4.6]
at Script1.run(Script1.groovy:2) ~[?:?]
at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:58) ~[hugegraph-loader-0.11.1.jar:?]
at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:156) ~[hugegraph-loader-0.11.1.jar:?]
at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:105) [hugegraph-loader-0.11.1.jar:?]
at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:71) [hugegraph-loader-0.11.1.jar:?]
Caused by: com.baidu.hugegraph.exception.ServerException$ServerCause: java.io.InterruptedIOException
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.t.TaskManager [] - Waiting for the insert tasks finished
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.t.TaskManager [] - The batch-mode tasks stopped
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.t.TaskManager [] - The single-mode tasks stopped
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.t.TaskManager [] - The batch-mode tasks service executor shutdown
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.t.TaskManager [] - The single-mode tasks service executor shutdown
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.e.LoadContext [] - Close all failure loggers successfully
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.e.LoadContext [] - Write load progress successfully
2021-08-13 11:42:35 [main] [INFO ] c.b.h.l.e.LoadContext [] - Close HugeClient successfully
2021-08-13 11:42:35 [Thread-3] [INFO ] c.b.h.l.HugeGraphLoader [] - Shutdown hook was triggered

**Comment by imbajin** [comment]
你从 #175 可以看到正常来说是可以支持的, 而且理论上它只跟 server 相关, 因为server 充当了 hbase-client 的角色

从报错也看不到 loader 的信息, 还是先确认 server 的各项配置都正常无误, 另外你也可以从 kerberos 那个 PR 的评论区参考一下

**Comment by wanglunwei** [comment]
使用HugeGraph-Hubble可以导入到开启Kerberos的hugegraph中，这个说明server端没有问题，但是使用HugeGraph-Loader导入报上述的错误，也不知道哪里的问题。

**Comment by wanglunwei** [comment]
Loader报错是在调用createSchema方法中的script.run();报的错误，如下图：
![1629014589(1)](https://user-images.githubusercontent.com/25580327/129471542-38325bb6-7a0a-44ea-9a14-217eedc0b754.png)

![1629014627(1)](https://user-images.githubusercontent.com/25580327/129471534-7068cc85-ff0b-4705-8b05-3e1f26f98007.png)

**Comment by imbajin** [comment]
> 使用HugeGraph-Hubble可以导入到开启Kerberos的hugegraph中，这个说明server端没有问题，但是使用HugeGraph-Loader导入报上述的错误，也不知道哪里的问题。

你可以在 loader 里添加一些日志, loader 的测试类里可以直接运行(无需重新打包), 然后看看异常具体抛出在什么地方, 确定一下
