### ISSUE TITLE
hugegraph-spark-loader.sh spark on yarn时--queue指定队列失败

### ISSUE THREAD

**Issue by haohao0103** [apache/incubator-hugegraph-toolchain#292]
### Bug Type (问题类型)

others (please comment below)

### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Toolchain-Issues](https://github.com/hugegraph/hugegraph-loader/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Loader Version: v0.12.x
- Data Size:  50w vertices, 200w edges 

### Expected & Actual behavior (期望与实际表现)

导入数据任务脚本：
./bin/hugegraph-spark-loader.sh 
--master yarn  \
--deploy-mode client \
--queue queue_name \
--username admin  \
--token admin  \
--name spark-test\  
-g hugegraph -f /home/data/struct.json -s /home/data/schema.groovy \
--batch-size 500 -h x.x.x.x  -p 8080

报错信息：
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/30570711/173827464-093b3cc3-3bb5-4872-97a1-4a97bbdc84ac.png">
22/06/15 20:31:06 ERROR Printer: Failed to start loading, cause: Was passed main parameter '--queue' but no main parameter was defined in your arg class
com.beust.jcommander.ParameterException: Was passed main parameter '--queue' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at com.baidu.hugegraph.loader.executor.LoadOptions.parseOptions(LoadOptions.java:216)
	at com.baidu.hugegraph.loader.spark.HugeGraphSparkLoader.<init>(HugeGraphSparkLoader.java:80)
	at com.baidu.hugegraph.loader.spark.HugeGraphSparkLoader.main(HugeGraphSparkLoader.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Failed to start loading, cause: Was passed main parameter '--queue' but no main parameter was defined in your arg class
原因：
脚本解析对spark-submit所需参数处理不全，导致部分spark-submit.sh脚本的参数被当成HugeGraphSparkLoader的参数使用
![image](https://user-images.githubusercontent.com/30570711/173828061-534c2990-8fc0-4c4e-9895-415d85cc7381.png)

**Comment by simon824** [comment]
@haohao0103  hi,  thanks for your feedback, this bug has been fix in #291 , you can try again after #291 merged later.
