### ISSUE TITLE
[Bug]  Jackson Conflicting property-based creators Exception

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph-toolchain#373]
### Before submit

- [X] I had searched in the [issues](https://github.com/hugegraph/hugegraph-loader/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v0.12.x
- Loader Version: v0.12.x
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

./bin/hugegraph-loader.sh -g test -f ./test.json -h 127.0.0.1 -p 8093 

```
2022-11-21 14:12:36 [main] [ERROR] o.a.h.l.u.Printer [] - Failed to start loading, cause: Failed to deserialize json
org.apache.hugegraph.rest.SerializeException: Failed to deserialize json
	at org.apache.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:77) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.util.MappingUtil.parse(MappingUtil.java:84) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.mapping.LoadMapping.of(LoadMapping.java:68) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:80) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:76) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:67) ~[hugegraph-loader-1.0.0.jar:1.0.0]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had explicitly marked creator [constructor for `org.apache.hugegraph.loader.mapping.LoadMapping` (2 args), annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}, encountered another: [constructor for `org.apache.hugegraph.loader.mapping.LoadMapping` (1 arg), annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}
 at [Source: (String)"{
    "version":"2.0",
    "structs":[
        {
            "id":"1",
            "skip":false,
            "input":{
                "custom_sql":"select a,b from table limit 10",
                "type":"JDBC",
                "table":"test",
                "vendor":"mysql",
                "driver":"com.mysql.cj.jdbc.Driver",
                "url":"jdbc:mysql://xxxx:xxxx",
                "database":"db",
                "schema"[truncated 276 chars]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:269) ~[jackson-databind-2.14.0.jar:2.14.0]
{
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:648) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4861) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4731) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.0.jar:2.14.0]
	at org.apache.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:74) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	... 5 more
Caused by: java.lang.IllegalArgumentException: Conflicting property-based creators: already had explicitly marked creator [constructor for `org.apache.hugegraph.loader.mapping.LoadMapping` (2 args), annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}, encountered another: [constructor for `org.apache.hugegraph.loader.mapping.LoadMapping` (1 arg), annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}
	at com.fasterxml.jackson.databind.deser.impl.CreatorCollector._reportDuplicateCreator(CreatorCollector.java:364) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.impl.CreatorCollector.verifyNonDup(CreatorCollector.java:326) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.impl.CreatorCollector.addPropertyCreator(CreatorCollector.java:179) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitAnyCreator(BasicDeserializerFactory.java:989) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitConstructorCreators(BasicDeserializerFactory.java:474) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:304) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:262) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:648) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4861) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4731) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.0.jar:2.14.0]
	at org.apache.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:74) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	... 5 more
```

**Comment by simon824** [comment]
@JackyYangPassion
