### ISSUE TITLE
[Bug] java8 loader error

### ISSUE THREAD

**Issue by JackyYangPassion** [apache/incubator-hugegraph-toolchain#403]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.0.0
- Toolchain Version: v1.0.0

### Expected & Actual behavior (期望与实际表现)

wget  https://dist.apache.org/repos/dist/dev/incubator/hugegraph/1.0.0/apache-hugegraph-toolchain-incubating-1.0.0.tar.gz

**env**：mac  java8 
**loader**: apache-hugegraph-toolchain-incubating-1.0.0.tar.gz
**cmd**：sh bin/hugegraph-loader.sh -g hugegraph -f example/file/struct.json -s example/file/schema.groovy
**ERROR**：
```
2023-01-01 13:50:20 [main] [ERROR] o.a.h.l.u.Printer [] - Failed to load, cause: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
java.lang.RuntimeException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.apache.hugegraph.loader.util.LoadUtil.targetRuntimeException(LoadUtil.java:71) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:113) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:72) ~[hugegraph-loader-1.0.0.jar:1.0.0]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.apache.hugegraph.loader.builder.ElementBuilder.checkVertexIdLength(ElementBuilder.java:285) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.builder.ElementBuilder.access$700(ElementBuilder.java:61) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.builder.ElementBuilder$VertexPkKVPairs.buildVertices(ElementBuilder.java:545) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:61) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.task.ParseTaskBuilder.lambda$buildTask$0(ParseTaskBuilder.java:98) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.task.ParseTaskBuilder$ParseTask.get(ParseTaskBuilder.java:160) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.executeParseTask(HugeGraphLoader.java:287) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.loadStruct(HugeGraphLoader.java:261) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.loadStructs(HugeGraphLoader.java:218) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:200) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:172) ~[hugegraph-loader-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109) ~[hugegraph-loader-1.0.0.jar:1.0.0]
```

**Comment by imbajin** [comment]
the root problem is `ByteBuffer` is not compatible fully between java11 & java8, refer a stackoverflow

**Comment by javeme** [comment]
we can try this method:
- https://juejin.cn/post/7048869257966256164
- https://github.com/apache/incubator-hugegraph-toolchain/blob/70a2100f41c2e85bdf51aa5766b7921a9febf49f/hugegraph-loader/pom.xml#L609

or take a workaround method: convert ByteBuffer to Buffer before the clear() call:
- https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime
- https://issues.apache.org/jira/browse/MRESOLVER-85
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=564520
