### ISSUE TITLE
Spark loader has dependency conflicts

### ISSUE THREAD

**Issue by haohao0103** [apache/incubator-hugegraph-toolchain#464]
### Bug Type (问题类型)

None

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.0.0
- Toolchain Version: v1.0.0

### Expected & Actual behavior (期望与实际表现)

When running spark-loader, there were a lot of dependency conflicts. Finally, I found the jersey,jakarta,hk2 related package, which was in spark's jars directory, and it was not the same as the jersey,jakarta,hk2 version in the lib directory after the loader was packaged. For example, lib has mainly 3.x jersey and spark has 2.x jars. My solution was to remove the conflicting jars from the spark jars directory and use the loader as it was, so the loader could run. Screenshot of error message:
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/30570711/e77f7432-1708-4c11-a52e-afd79105f14a)
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/30570711/590a0c54-8ac7-4cb5-9fa7-adabc1eaabb4)

The simple removal of the jar worked for me but wasn't general enough. I'm trying to use spark-submit --exclude-jars and see if the community has a better solution, thanks

**Comment by imbajin** [comment]
seems our spark loader meets some exception now #404, consider fix/ensure them as a tiny task? @simon824

**Comment by simon824** [comment]
Solve this issue by `shade`? 
what do you think? @haohao0103 @JackyYangPassion @imbajin @liuxiaocs7

**Comment by haohao0103** [comment]
> Solve this issue by `shade`? what do you think? @haohao0103 @JackyYangPassion @imbajin @liuxiaocs7

thanks, I tried to specify that userclasspath has higher priority but I was blocked by many other issues. Use shade plugin relocation to solve this problem, right? There are a few conflicting jars, but it's a good idea I can try

**Comment by imbajin** [comment]
> > Solve this issue by `shade`? what do you think? @haohao0103 @JackyYangPassion @imbajin @liuxiaocs7
> 
> thanks, I tried to specify that userclasspath has higher priority but I was blocked by many other issues. Use shade plugin relocation to solve this problem, right? There are a few conflicting jars, but it's a good idea I can try

address this issue, any update with it?

**Comment by haohao0103** [comment]
@imbajin hello, I am following up on this matter. The local test basically passed. I will submit a pr as soon as possible.thanks

**Comment by haohao0103** [comment]
@liuxiaocs7 
hello, the conflict I'm trying to resolve is exactly what you described !!!
after the shad-shaped jar is successfully packaged, you can run bin/hugegraph-spark-loader.sh to test it.
as for  how to run in IDE?  
I understand that since we set spark dependency to provided, we can't run in the IDE. Before shade, we can run temporary tests in IDE by modifying the scope that spark depends on, but now I think it is not possible.If we change the scope of spark dependency, we need to adjust the shade strategy to match whether spark dependency is external or existing in the project。

**Comment by z7658329** [comment]
> 

@haohao0103 @liuxiaocs7  
1. can we refer to how the Spark community deals with the issue of javax and Jakarta package names ?
2. in this case, can exclude jakarta.servlet-api in spark-core_2.12, and add manual? because jakarta.servlet-api-4.0.x use javax but change to jakarta from version 5.0.0 ,  so we can upgrade to 5.0.0, see : 

```
         <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.12</artifactId>
            <version>3.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.servlet</groupId>
                    <artifactId>jakarta.servlet-api</artifactId>
                </exclusion>
                
                ......
                
            </exclusions>
        </dependency>


        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>5.0.0</version>
        </dependency>
```

**Comment by liuxiaocs7** [comment]
Hi, @z7658329, I have tried to manually specify the version of jakarta.servlet-api as 5.0.0 or 6.0.0 instead of the default 4.0.3, and got the following results


```shell
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/Servlet
	at org.apache.spark.ui.SparkUI$.create(SparkUI.scala:183)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:480)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at top.liuxiaocs.Main.main(Main.java:16)
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 4 more
```

pom:

```xml
<dependencies>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.12</artifactId>
        <version>3.2.2</version>
        <scope>provided</scope>
        <exclusions>
            <exclusion>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_2.12</artifactId>
        <version>3.2.2</version>
        <scope>provided</scope>
        <exclusions>
            <exclusion>
                <artifactId>antlr4-runtime</artifactId>
                <groupId>org.antlr</groupId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>org.apache.hugegraph</groupId>
        <artifactId>hugegraph-client</artifactId>
        <version>1.0.0</version>
        <exclusions>
            <!-- Note: jackson version should < 2.13 with scala 2.12 -->
            <exclusion>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>*</artifactId>
            </exclusion>
            <exclusion>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>*</artifactId>
            </exclusion>
            <exclusion>
                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                <artifactId>*</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>jakarta.servlet</groupId>
        <artifactId>jakarta.servlet-api</artifactId>
        <version>5.0.0</version>
    </dependency>
</dependencies>
```

**Comment by liuxiaocs7** [comment]
> @liuxiaocs7 hello, the conflict I'm trying to resolve is exactly what you described !!! after the shaded jar is successfully packaged, you can run bin/hugegraph-spark-loader.sh to test it. as for how to run in IDE? I understand that since we set spark dependency to provided, we can't run in the IDE. Before shade, we can run temporary tests in IDE by modifying the scope that spark depends on, but now I think it is not possible.If we change the scope of spark dependency, we need to adjust the shade strategy to match whether spark dependency is external or existing in the project。

Thank you for your detailed explanation. I will try it based on your PR. As for the dependency whose scope is provide, you can check this option in IDEA.

![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/42756849/be27484f-139e-4412-86d1-3146f82ed2b4)

> but now I think it is not possible.If we change the scope of spark dependency, we need to adjust the shade strategy to match whether spark dependency is external or existing in the project

Yeap, they cannot coexist in IDEA

**Comment by liuxiaocs7** [comment]
A minimal runnable Spark3.2.2+HugeGraph-Client1.0.0 example: https://github.com/liuxiaocs7/HugeGraphSpark

**Comment by haohao0103** [comment]
@liuxiaocs7 Thank you very much. I didn't know it was possible to do this without modifying the pom file.
