### ISSUE TITLE
[Bug] start server error : Expect just one result, but got at least two

### ISSUE THREAD

**Issue by DirkJia** [apache/incubator-hugegraph-toolchain#476]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v0.11.2-b4
- Java Version: v1.8.x
- Data Size:  267199 vertices, 310555 edges
- Backend Store ：cassandra V3.11.9

### Expected & Actual behavior (期望与实际表现)

运行很长一段时间后出现报错，提示两个backend info

```java
Exception in thread "main" com.baidu.hugegraph.HugeException: Expect just one result, but got at least two: [TableBackendEntry{Row{type=PROPERTY_KEY, id=null, columns={USER_DATA={version="1.9", ~create_time="2022-07-20 01:49:37.887"}, AGGREGATE_TYPE=0, PROPERTIES=[], NAME=~backend_info, DATA_TYPE=8, STATUS=1, ID=-33, CARDINALITY=1}}, sub-rows: []}, TableBackendEntry{Row{type=PROPERTY_KEY, id=null, columns={USER_DATA={version="1.9", ~create_time="2023-06-02 09:58:38.300"}, AGGREGATE_TYPE=0, PROPERTIES=[], NAME=~backend_info, DATA_TYPE=8, STATUS=1, ID=-1397, CARDINALITY=1}}, sub-rows: []}]
        at com.baidu.hugegraph.backend.query.QueryResults.one(QueryResults.java:228)
        at com.baidu.hugegraph.backend.query.QueryResults.one(QueryResults.java:87)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:327)
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:240)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:128)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:72)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:92)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:116)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:99)
```

**Comment by imbajin** [comment]
is this a server problem？（seems not a toolchain pic）

and do u try the latest version（apache 1.0.0）？

**Comment by DirkJia** [comment]
> is this a server problem？（seems not a toolchain pic）
> 
> and do u try the latest version（apache 1.0.0）？

yes，it happened too suddenly, can I have a temporary solution instead of upgrading now?

**Comment by DirkJia** [comment]
> is this a server problem？（seems not a toolchain pic）
> 
> and do u try the latest version（apache 1.0.0）？
Is it necessary to raise another issue for project of incubator-hugegraph？

**Comment by DirkJia** [comment]
> is this a server problem？（seems not a toolchain pic）
> 
> and do u try the latest version（apache 1.0.0）？

Is it necessary to raise another issue for project of [incubator-hugegraph](https://github.com/apache/incubator-hugegraph)?

**Comment by DirkJia** [comment]
> is this a server problem？（seems not a toolchain pic）
> 
> and do u try the latest version（apache 1.0.0）？

Do I need to delete the data in the  the table of pk ? Also, in what scenarios would this situation typically occur?

**Comment by imbajin** [comment]
> > is this a server problem？（seems not a toolchain pic）
> > 
> > and do u try the latest version（apache 1.0.0）？
> 
> Is it necessary to raise another issue for project of [incubator-hugegraph](https://github.com/apache/incubator-hugegraph)?

nope，and the issue could transfer directly （but we need more time for the outdated version）

**Comment by DirkJia** [comment]
> > > is this a server problem？（seems not a toolchain pic）
> > > and do u try the latest version（apache 1.0.0）？
> > 
> > 
> > Is it necessary to raise another issue for project of [incubator-hugegraph](https://github.com/apache/incubator-hugegraph)?
> 
> nope，and the issue could transfer directly （but we need more time for the outdated version）
> 
> also u could add some backend info（edit the top comment）

done. and i am I deleting data by tracing the code. If it doesn't work, I shall  switch to another Cassandra database to try it out

**Comment by DirkJia** [comment]
> > > > is this a server problem？（seems not a toolchain pic）
> > > > and do u try the latest version（apache 1.0.0）？
> > > 
> > > 
> > > Is it necessary to raise another issue for project of [incubator-hugegraph](https://github.com/apache/incubator-hugegraph)?
> > 
> > 
> > nope，and the issue could transfer directly （but we need more time for the outdated version）
> > also u could add some backend info（edit the top comment）
> 
> done. and i am I deleting data by tracing the code. If it doesn't work, I shall switch to another Cassandra database to try it out

I deleted some duplicate data from the tables like vl,il,el,pk,c etc，and now it's working fine。

I suspect that Cassandra has three nodes in total, and two of them were restarted, causing HugeGraph to not read the metadata. Therefore, the metadata was written again. When Cassandra is back to normal, the data became duplicated, causing the HugeGraph verification to fail. I am not sure if the new version has fixed this issue?
