### ISSUE TITLE
[Improve] Update loader package shade plugin

### ISSUE THREAD

**Issue by liuxiaocs7** [apache/incubator-hugegraph-toolchain#562]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

- Cause: https://github.com/apache/incubator-hugegraph-toolchain/issues/464
- Solution: https://github.com/apache/incubator-hugegraph-toolchain/pull/480
- After introducing okhttp by https://github.com/apache/incubator-hugegraph-toolchain/pull/538, we need to recheck the packaging

![img_v3_0265_930f7666-0731-4b83-b4c5-cda67a725deg](https://github.com/apache/incubator-hugegraph-toolchain/assets/42756849/7c7ef04a-0003-4f9f-af74-b186b1ddd51d)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuxiaocs7** [comment]
```bash
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
        at org.apache.hugegraph.util.E.checkNotNull(E.java:29)
        at org.apache.hugegraph.api.API.<init>(API.java:35)
        at org.apache.hugegraph.api.version.VersionAPI.<init>(VersionAPI.java:29)
        at org.apache.hugegraph.driver.VersionManager.<init>(VersionManager.java:29)
        at org.apache.hugegraph.driver.HugeClient.initManagers(HugeClient.java:96)
        at org.apache.hugegraph.driver.HugeClient.<init>(HugeClient.java:69)
        at org.apache.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:62)
        at org.apache.hugegraph.loader.util.HugeClientHolder.create(HugeClientHolder.java:72)
        at org.apache.hugegraph.loader.executor.LoadContext.<init>(LoadContext.java:71)
        at org.apache.hugegraph.loader.spark.HugeGraphSparkLoader.initPartition(HugeGraphSparkLoader.java:200)
        at org.apache.hugegraph.loader.spark.HugeGraphSparkLoader.lambda$null$18e75a97$1(HugeGraphSparkLoader.java:156)
        at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$2(Dataset.scala:2923)
        at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$2$adapted(Dataset.scala:2923)
        at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
        at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2254)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```
